#Rank Customers by Total Sales
#who are the top revenue-generating customers?
SELECT 
    customername,
    ROUND(SUM(sales),2) AS total_sales,
    RANK() OVER (ORDER BY SUM(sales) DESC) AS sales_rank
FROM superstore
GROUP BY customername;



#Running Total of Sales Over Time
#cumulative revenue growth
SELECT 
    orderdate,
    ROUND(SUM(sales),2) AS daily_sales,
    ROUND(SUM(SUM(sales)) OVER (ORDER BY orderdate),2) AS running_total_sales
FROM superstore
GROUP BY orderdate
ORDER BY orderdate;

#Rank Regions by Profit
#which region is most profitable?
SELECT 
    region,
    ROUND(SUM(profit),2) AS total_profit,
    DENSE_RANK() OVER (ORDER BY SUM(profit) DESC) AS profit_rank
FROM superstore
GROUP BY region;

#Customer Lifetime Value (CLV)
#total value generated by each customer
SELECT 
    customername,
    ROUND(SUM(sales) OVER (PARTITION BY customername),2) AS lifetime_sales,
    ROUND(SUM(profit) OVER (PARTITION BY customername),2) AS lifetime_profit
FROM superstore;

#Identify First & Latest Purchase of Each Customer
#customer journey analysis
SELECT 
    customername,
   orderdate,
    ROW_NUMBER() OVER (PARTITION BY customername ORDER BY orderdate) AS purchase_order
FROM superstore;

#Average Sales per Order vs Overall Average
#compare order performance
SELECT 
    orderid,
    ROUND(SUM(sales),2) AS order_sales,
    ROUND(AVG(SUM(sales)) OVER (),2) AS overall_avg_sales
FROM superstore
GROUP BY orderid;

#Profit Difference Between Consecutive Orders (LEAD)
#profit volatility analysis

SELECT 
    orderdate,
    profit,
    LEAD(profit) OVER (ORDER BY orderdate) AS next_order_profit,
    ROUND(LEAD(profit) OVER (ORDER BY orderdate) - profit,2) AS profit_change
FROM superstore;
